Shell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\aredl> mkdir DockerProject


    Directory: C:\Users\aredl


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     19:33                DockerProject


PS C:\Users\aredl> cd DockerProject
PS C:\Users\aredl\DockerProject> mkdir data


    Directory: C:\Users\aredl\DockerProject


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     19:33                data


PS C:\Users\aredl\DockerProject> New-Item -Path . -Name "Dockerfile" -ItemType "file"


    Directory: C:\Users\aredl\DockerProject


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        27-02-2025     19:35              0 Dockerfile


PS C:\Users\aredl\DockerProject> cd path\to\DockerProject
cd : Cannot find path 'C:\Users\aredl\DockerProject\path\to\DockerProject' because it does not exist.
At line:1 char:1
+ cd path\to\DockerProject
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\aredl\...o\DockerProject:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\aredl\DockerProject> cd "C:\Users\aredl\DockerProject"
PS C:\Users\aredl\DockerProject> New-Item -Path . -Name "scripts.py" -ItemType "file"


    Directory: C:\Users\aredl\DockerProject


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        27-02-2025     19:48              0 scripts.py


PS C:\Users\aredl\DockerProject> docker build -t text-processor .
[+] Building 0.2s (1/1) FINISHED                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 31B                                                                                0.0s
ERROR: failed to solve: the Dockerfile cannot be empty
PS C:\Users\aredl\DockerProject> docker build -t text-processor .
[+] Building 16.9s (12/12) FINISHED                                                                docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 451B                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                 1.5s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [1/6] FROM docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b  5.1s
 => => resolve docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b  0.0s
 => => sha256:fb0009da06dd4711325d429d94e351cbe2d79521e8c70885ddf3282f48baa8de 250B / 250B                         0.1s
 => => sha256:09f8c21e9f8e95147eea7783b9c462268cdeb1b26f4f68790a0d4e1e29396976 14.94MB / 14.94MB                   1.4s
 => => sha256:82a59f028fa3e4c2c425073b77d0bfde2d9aa166cf413b6f1ceac275585e8027 3.51MB / 3.51MB                     0.7s
 => => sha256:7cf63256a31a4cc44f6defe8e1af95363aee5fa75f30a248d95cae684f87c53c 28.22MB / 28.22MB                   2.9s
 => => extracting sha256:7cf63256a31a4cc44f6defe8e1af95363aee5fa75f30a248d95cae684f87c53c                          1.1s
 => => extracting sha256:82a59f028fa3e4c2c425073b77d0bfde2d9aa166cf413b6f1ceac275585e8027                          0.2s
 => => extracting sha256:09f8c21e9f8e95147eea7783b9c462268cdeb1b26f4f68790a0d4e1e29396976                          0.6s
 => => extracting sha256:fb0009da06dd4711325d429d94e351cbe2d79521e8c70885ddf3282f48baa8de                          0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 115B                                                                                  0.0s
 => [2/6] WORKDIR /home                                                                                            0.2s
 => [3/6] COPY scripts.py /home/scripts.py                                                                         0.1s
 => [4/6] COPY data /home/data                                                                                     0.1s
 => [5/6] RUN pip install --no-cache-dir requests nltk                                                             6.8s
 => [6/6] RUN chmod +x /home/scripts.py                                                                            0.5s
 => exporting to image                                                                                             2.3s
 => => exporting layers                                                                                            1.5s
 => => exporting manifest sha256:5d875749cf823627e56b67f1853f19845f5eb21955ab7ca7e6c625f62769a28a                  0.0s
 => => exporting config sha256:31bed1446bf8624010a0c14ad52906039e4b44e76c43d20fd4f20be17ae50be9                    0.0s
 => => exporting attestation manifest sha256:f4baeffdec2deb2f9c96f1950bacfe8d2a9311ba4edc826d7e33b011c9d38fb3      0.0s
 => => exporting manifest list sha256:082366939cec43d6ef9d7ce5cd8d18f5945fdb01e2f3590bc5d39fc355b60021             0.0s
 => => naming to docker.io/library/text-processor:latest                                                           0.0s
 => => unpacking to docker.io/library/text-processor:latest                                                        0.7s
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:\Users\aredl\Dockerproject\data:C:\home\data" text
                               > docker run --rm -v "C:\Users\aredl\Dockerproject\data:C:\home\data" text-processor
docker: Error response from daemon: invalid mode: \home\data.
See 'docker run --help'.
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:\Users\aredl\Dockerproject\data:C:" text-processor
docker: Error response from daemon: invalid volume specification: '/run/desktop/mnt/host/c/Users/aredl/DockerProject/data:C:': invalid mount config for type "bind": invalid mount path: 'C' mount path must be absolute.
See 'docker run --help'.
PS C:\Users\aredl\DockerProject> docker run --rm -v "/c/Users/aredl/Dockerproject/data:/home/data" text-processor
Hello from inside the Docker container!
Traceback (most recent call last):
  File "/home/scripts.py", line 23, in <module>
    word_count_1 = count_words(file1)
  File "/home/scripts.py", line 18, in count_words
    with open(filepath, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/IF-1.txt'
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:\Users\aredl\DockerProject\data:C:\home\data" text-processor
docker: Error response from daemon: invalid mode: \home\data.
See 'docker run --help'.
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 23, in <module>
    word_count_1 = count_words(file1)
  File "/home/scripts.py", line 18, in count_words
Hello from inside the Docker container!
    with open(filepath, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/IF-1.txt'
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 23, in <module>
    word_count_1 = count_words(file1)
  File "/home/scripts.py", line 18, in count_words
    with open(filepath, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/IF-1.txt'
Hello from inside the Docker container!
PS C:\Users\aredl\DockerProject> ls


    Directory: C:\Users\aredl\DockerProject


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     20:35                data
d-----        27-02-2025     20:09                data;C
-a----        27-02-2025     19:55            412 Dockerfile
-a----        27-02-2025     20:26           1915 scripts.py


PS C:\Users\aredl\DockerProject> cd ..
PS C:\Users\aredl> mkdir home


    Directory: C:\Users\aredl


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     21:08                home


PS C:\Users\aredl> cd home
PS C:\Users\aredl\home> mkdir data


    Directory: C:\Users\aredl\home


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     21:08                data


PS C:\Users\aredl\home> ls


    Directory: C:\Users\aredl\home


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     21:08                data


PS C:\Users\aredl\home> cd data
PS C:\Users\aredl\home\data> pwd

Path
----
C:\Users\aredl\home\data


PS C:\Users\aredl\home\data> docker run --rm -v "C:/Users/aredl/DockerProject/data:C:\Users\aredl\home\data" text-processor
docker: Error response from daemon: invalid mode: \Users\aredl\home\data.
See 'docker run --help'.
PS C:\Users\aredl\home\data> cd ..
PS C:\Users\aredl\home> cd ..
PS C:\Users\aredl> cd .\DockerProject\
PS C:\Users\aredl\DockerProject> ls


    Directory: C:\Users\aredl\DockerProject


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     20:35                data
d-----        27-02-2025     20:09                data;C
-a----        27-02-2025     19:55            412 Dockerfile
-a----        27-02-2025     20:26           1915 scripts.py


PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:C:\Users\aredl\home\data" text-processor
docker: Error response from daemon: invalid mode: \Users\aredl\home\data.
See 'docker run --help'.
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 23, in <module>
Hello from inside the Docker container!
    word_count_1 = count_words(file1)
  File "/home/scripts.py", line 18, in count_words
    with open(filepath, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/IF-1.txt'
PS C:\Users\aredl\DockerProject> ls


    Directory: C:\Users\aredl\DockerProject


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     20:35                data
d-----        27-02-2025     20:09                data;C
-a----        27-02-2025     19:55            412 Dockerfile
-a----        27-02-2025     20:26           1915 scripts.py


PS C:\Users\aredl\DockerProject> cddata
cddata : The term 'cddata' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ cddata
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (cddata:String) [], CommandN
   otFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> cd data
PS C:\Users\aredl\DockerProject\data> ls


    Directory: C:\Users\aredl\DockerProject\data


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27-02-2025     20:24                output
-a----        27-02-2025     20:28              0 IF-1.txt.txt


PS C:\Users\aredl\DockerProject\data> cd ..
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Hello from inside the Docker container!
Traceback (most recent call last):
  File "/home/scripts.py", line 24, in <module>
    word_count_2 = count_words(file2)
  File "/home/scripts.py", line 18, in count_words
    with open(filepath, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/data/AlwaysRememberUsThisWay-1.txt'
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Hello from inside the Docker container!
Total words in IF-1.txt: 0
Total words in AlwaysRememberUsThisWay-1.txt: 0
Grand total: 0
Top 3 words in IF-1.txt: []
Top 3 words in AlwaysRememberUsThisWay-1.txt (handling contractions): []
Container IP Address: 172.17.0.3

PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Hello from inside the Docker container!
Total words in IF-1.txt: 6
Total words in AlwaysRememberUsThisWay-1.txt: 0
Grand total: 6
Top 3 words in IF-1.txt: [('hi', 1), ('i', 1), ('am', 1)]
Top 3 words in AlwaysRememberUsThisWay-1.txt (handling contractions): []
Container IP Address: 172.17.0.3

PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Hello from inside the Docker container!
Traceback (most recent call last):
  File "/home/scripts.py", line 23, in <module>
    word_count_1 = count_words(file1)
  File "/home/scripts.py", line 19, in count_words
    words = re.findall(r"\b\w+(?:'\w+)?\b", f.read().lower())
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 23, in <module>
Hello from inside the Docker container!
    word_count_1 = count_words(file1)
  File "/home/scripts.py", line 19, in count_words
    words = re.findall(r"\b\w+(?:'\w+)?\b", f.read().lower())
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Hello from inside the Docker container!
Traceback (most recent call last):
  File "/home/scripts.py", line 23, in <module>
    word_count_1 = count_words(file1)
  File "/home/scripts.py", line 19, in count_words
    words = re.findall(r"\b\w+(?:'\w+)?\b", f.read().lower())
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> docker build -t text-processor .
[+] Building 13.3s (11/11) FINISHED                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                   0.1s
 => => transferring dockerfile: 434B                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim     1.0s
 => [auth] library/python:pull token for registry-1.docker.io          0.0s
 => [internal] load .dockerignore                                      0.0s
 => => transferring context: 2B                                        0.0s
 => [1/5] FROM docker.io/library/python:3.9-slim@sha256:d1fd807555208  0.0s
 => => resolve docker.io/library/python:3.9-slim@sha256:d1fd807555208  0.0s
 => [internal] load build context                                      0.1s
 => => transferring context: 6.24kB                                    0.1s
 => CACHED [2/5] WORKDIR /home                                         0.0s
 => [3/5] COPY scripts.py /home/scripts.py                             0.1s
 => [4/5] COPY data /home/data                                         0.1s
 => [5/5] RUN pip install --no-cache-dir requests nltk                 9.4s
 => exporting to image                                                 2.3s
 => => exporting layers                                                1.5s
 => => exporting manifest sha256:63d28dd9124ecde0a5bd6f4b6c39bba167a9  0.0s
 => => exporting config sha256:751e0eb0122c7e306ccd2059f92556e7da6f11  0.0s
 => => exporting attestation manifest sha256:2cb461198538204e78fe3a52  0.0s
 => => exporting manifest list sha256:7f212b09dc279daac6404c1eec2c6c5  0.0s
 => => naming to docker.io/library/text-processor:latest               0.0s
 => => unpacking to docker.io/library/text-processor:latest            0.6s
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 20, in <module>
    words_in_file1 = count_words(file1)
  File "/home/scripts.py", line 12, in count_words
    text = f.read().lower()  # Read the file and convert text to lowercase
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 20, in <module>
    words_in_file1 = count_words(file1)
  File "/home/scripts.py", line 12, in count_words
    text = f.read().lower()  # Read the file and convert text to lowercase
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> ls /home/data
ls : Cannot find path 'C:\home\data' because it does not exist.
At line:1 char:1
+ ls /home/data
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\home\data:String) [Get-C
   hildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.G
   etChildItemCommand

PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 20, in <module>
    words_in_file1 = count_words(file1)
  File "/home/scripts.py", line 12, in count_words
    text = f.read().lower()  # Read the file and convert text to lowercase
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:\Users\aredl\DockerProject\data:C:\home\data" text-processor
docker: Error response from daemon: invalid mode: \home\data.
See 'docker run --help'.
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 20, in <module>
    words_in_file1 = count_words(file1)
  File "/home/scripts.py", line 12, in count_words
    text = f.read().lower()  # Read the file and convert text to lowercase
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
Traceback (most recent call last):
  File "/home/scripts.py", line 20, in <module>
    words_in_file1 = count_words(file1)
  File "/home/scripts.py", line 12, in count_words
    text = f.read().lower()  # Read the file and convert text to lowercase
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 276: invalid start byte
PS C:\Users\aredl\DockerProject> docker run --rm -v "C:/Users/aredl/DockerProject/data:/home/data" text-processor
File 1: /home/data/IF-1.txt
Word Count in File 1: 301
File 2: /home/data/AlwaysRememberUsThisWay-1.txt
Word Count in File 2: 242
Grand Total Word Count: 543
Top 3 Words in /home/data/IF-1.txt:
you: 20
and: 20
if: 14
Top 3 Words in /home/data/AlwaysRememberUsThisWay-1.txt (with expanded contractions):
i: 15
the: 13
t: 9
Container IP Address: 172.17.0.3

PS C:\Users\aredl\DockerProject> docker images text-processor
REPOSITORY       TAG       IMAGE ID       CREATED          SIZE
text-processor   latest    7f212b09dc27   44 minutes ago   227MB
PS C:\Users\aredl\DockerProject> docker save -o KANSKRI.tar text-processor
PS C:\Users\aredl\DockerProject> nano deployment.yaml
nano : The term 'nano' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ nano deployment.yaml
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (nano:String) [], CommandNot
   FoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> vi deployment.yaml
vi : The term 'vi' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ vi deployment.yaml
+ ~~
    + CategoryInfo          : ObjectNotFound: (vi:String) [], CommandNotFo
   undException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
error: error validating "deployment.yaml": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.; if you choose to ignore these errors, turn validation off with --validate=false
PS C:\Users\aredl\DockerProject> kubectl get pods > kube_output.txt
E0227 22:17:02.963771   20644 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:17:02.980107   20644 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:17:02.995870   20644 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:17:03.012035   20644 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:17:03.028123   20644 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\aredl\DockerProject> cat kube_output.txt
PS C:\Users\aredl\DockerProject> minikube start
minikube : The term 'minikube' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ minikube start
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (minikube:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> kubectl cluster-info
E0227 22:23:22.269179   22776 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:23:22.277518   22776 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:23:22.292611   22776 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:23:22.308112   22776 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
E0227 22:23:22.323817   22776 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml --validate=false
E0227 22:23:40.848738   30640 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it."
error: unable to recognize "deployment.yaml": Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\aredl\DockerProject> curl http://localhost:8080
curl : Unable to connect to the remote server
At line:1 char:1
+ curl http://localhost:8080
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest
   :HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Powe
   rShell.Commands.InvokeWebRequestCommand

PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
error: error validating "deployment.yaml": error validating data: failed to download openapi: Get "https://kubernetes.docker.internal:6443/openapi/v2?timeout=32s": EOF; if you choose to ignore these errors, turn validation off with --validate=false
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml --validate=false
E0227 22:33:57.304774   14744 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
error: unable to recognize "deployment.yaml": Get "https://kubernetes.docker.internal:6443/api?timeout=32s": EOF
PS C:\Users\aredl\DockerProject> curl http://localhost:8080
curl : Unable to connect to the remote server
At line:1 char:1
+ curl http://localhost:8080
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest
   :HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Powe
   rShell.Commands.InvokeWebRequestCommand

PS C:\Users\aredl\DockerProject> kubectl get pods > kube_output.txt
E0227 22:35:40.363622   22548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:35:50.521231   22548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:36:00.664454   22548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:36:10.745627   22548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:36:20.898509   22548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
Unable to connect to the server: EOF
PS C:\Users\aredl\DockerProject> cat kube_output.txt
PS C:\Users\aredl\DockerProject>
PS C:\Users\aredl\DockerProject> minikube start
minikube : The term 'minikube' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ minikube start
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (minikube:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> kubectl cluster-info
E0227 22:36:43.071466   19548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:36:53.200997   19548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:37:03.327527   19548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:37:13.456053   19548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:37:23.648455   19548 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
PS C:\Users\aredl\DockerProject> kubectl cluster-info
E0227 22:39:49.584459   21540 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:39:59.741306   21540 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:40:09.908730   21540 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:40:20.071109   21540 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:40:30.232518   21540 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
PS C:\Users\aredl\DockerProject> kubectl cluster-info
E0227 22:42:45.502974   10000 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:42:55.675588   10000 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:43:05.853808   10000 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:43:16.017873   10000 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:43:26.179672   10000 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
PS C:\Users\aredl\DockerProject> kubectl cluster-info
E0227 22:44:20.927526   23072 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:44:31.069827   23072 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:44:41.230355   23072 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:44:51.366361   23072 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:45:01.553151   23072 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
PS C:\Users\aredl\DockerProject> kubectl cluster-info
E0227 22:58:50.805709   11728 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:59:00.978751   11728 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:59:11.154003   11728 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:59:21.328066   11728 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"
E0227 22:59:31.485923   11728 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"https://kubernetes.docker.internal:6443/api?timeout=32s\": EOF"

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: EOF
PS C:\Users\aredl\DockerProject> kubectl cluster-info
Kubernetes control plane is running at https://kubernetes.docker.internal:6443
CoreDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
deployment.apps/text-processor-deployment created
PS C:\Users\aredl\DockerProject> kubectl get pods > kube_output.txt
PS C:\Users\aredl\DockerProject> cat kube_output.txt
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-8455fd77dd-jl8qm   0/1     ImagePullBackOff   0          47s
text-processor-deployment-8455fd77dd-kcpml   0/1     ImagePullBackOff   0          47s
PS C:\Users\aredl\DockerProject> kubectl delete -f deployment.yaml
deployment.apps "text-processor-deployment" deleted
PS C:\Users\aredl\DockerProject> docker swarm init
Swarm initialized: current node (mfhpxfwu3laqrsh5ea1ksqn4b) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-2u7ak7nyh18vccgffs45en18hlghb6xuwakyn5ho42flderugj-blg5erk344pquuhq7hya5kuiw 192.168.65.3:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

PS C:\Users\aredl\DockerProject> docker stack deploy -c docker-compose.yml textprocessor_stack
open docker-compose.yml: The system cannot find the file specified.
PS C:\Users\aredl\DockerProject> docker stack deploy -c docker-compose.yml textprocessor_stack
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
Creating network textprocessor_stack_default
Creating service textprocessor_stack_text-processor
PS C:\Users\aredl\DockerProject> docker service ls
ID             NAME                                 MODE         REPLICAS   IMAGE                   PORTS
tmxmz6vzx1xy   textprocessor_stack_text-processor   replicated   1/2        text-processor:latest
PS C:\Users\aredl\DockerProject> docker service ps textprocessor_stack_text-processor
ID             NAME                                       IMAGE
      NODE             DESIRED STATE   CURRENT STATE                    ERROR     PORTS
3yt5lcis6tk6   textprocessor_stack_text-processor.1       text-processor:latest   docker-desktop   Running         Running less than a second ago

wwxc73o5iypt    \_ textprocessor_stack_text-processor.1   text-processor:latest   docker-desktop   Shutdown        Complete 6 seconds ago

7pw4zmw84t2u    \_ textprocessor_stack_text-processor.1   text-processor:latest   docker-desktop   Shutdown        Complete 13 seconds ago

t1y1wq883ii8    \_ textprocessor_stack_text-processor.1   text-processor:latest   docker-desktop   Shutdown        Complete 20 seconds ago

bh16ar4y6raw   textprocessor_stack_text-processor.2       text-processor:latest   docker-desktop   Ready           Ready less than a second ago

95iw0z9gsmgh    \_ textprocessor_stack_text-processor.2   text-processor:latest   docker-desktop   Shutdown        Complete 1 second ago

yarahjuafo07    \_ textprocessor_stack_text-processor.2   text-processor:latest   docker-desktop   Shutdown        Complete 7 seconds ago

wxojtmtxz497    \_ textprocessor_stack_text-processor.2   text-processor:latest   docker-desktop   Shutdown        Complete 14 seconds ago
PS C:\Users\aredl\DockerProject>
PS C:\Users\aredl\DockerProject> stack_text-processor.2   text-processor:latest   docker-desktop   Shutdown        Complete 20 seconds ago
PS C:\Users\aredl\DockerProject>
PS C:\Users\aredl\DockerProject> docker stack rm textprocessor_stack
PS C:\Users\aredl\DockerProject> ack_text-processor
PS C:\Users\aredl\DockerProject> ack_default
PS C:\Users\aredl\DockerProject> docker swarm leave --force
PS C:\Users\aredl\DockerProject>
PS C:\Users\aredl\DockerProject>
PS C:\Users\aredl\DockerProject> kubectl cluster-info
Kubernetes control plane is running at https://kubernetes.docker.internal:6443
CoreDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
PS C:\Users\aredl\DockerProject> docker swarm init
Swarm initialized: current node (4zn34lgtjlyxgsvq5njetc63p) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-2tmxp1d3luy4m163ix6b0qr3w30odonuej29x5m3lkgqhw2ggi-dbxzv5gah5nui2l7ndms2rfxp 192.168.65.3:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

PS C:\Users\aredl\DockerProject> docker stack deploy -c docker-compose.yml textprocessor_stack
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
Creating network textprocessor_stack_default
Creating service textprocessor_stack_text-processor
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
deployment.apps/text-processor-deployment created
PS C:\Users\aredl\DockerProject> kubectl get pods > kube_output.txt
PS C:\Users\aredl\DockerProject> cat kube_output.txt
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-8455fd77dd-ldfph   0/1     ImagePullBackOff   0          11s
text-processor-deployment-8455fd77dd-nkkvc   0/1     ImagePullBackOff   0          11s
PS C:\Users\aredl\DockerProject> kubectl get deployments
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
text-processor-deployment   0/2     2            0           113s
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-8455fd77dd-ldfph   0/1     ErrImagePull       0          113s
text-processor-deployment-8455fd77dd-nkkvc   0/1     ImagePullBackOff   0          113s
PS C:\Users\aredl\DockerProject> image: text-processor:latest
image: : The term 'image:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ image: text-processor:latest
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (image::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> docker build -t text-processor:latest .
[+] Building 11.9s (11/11) FINISHED                                                                                                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                   0.1s
 => => transferring dockerfile: 434B                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                     1.1s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [1/5] FROM docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.1s
 => => resolve docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.1s
 => [internal] load build context                                                                                                                      0.0s
 => => transferring context: 3.27kB                                                                                                                    0.0s
 => CACHED [2/5] WORKDIR /home                                                                                                                         0.0s
 => CACHED [3/5] COPY scripts.py /home/scripts.py                                                                                                      0.0s
 => [4/5] COPY data /home/data                                                                                                                         0.1s
 => [5/5] RUN pip install --no-cache-dir requests nltk                                                                                                 8.4s
 => exporting to image                                                                                                                                 1.9s
 => => exporting layers                                                                                                                                1.3s
 => => exporting manifest sha256:5cb06e83338bda13c75c1428a8fadc3c2b0980703e5b9f0d94a7c884275636dc                                                      0.0s
 => => exporting config sha256:b467010714fa9aca7ae45540cbec609e558bdd04a5f45b4aa590f01f01612fb5                                                        0.0s
 => => exporting attestation manifest sha256:ce1b0f44f61a984daae1dd313f53b503baa73ec21721946d88277a008aee2948                                          0.0s
 => => exporting manifest list sha256:5f37e852d759c1636152cd37d2f8b31442e6bea49e18d18881c1af727a7c44dd                                                 0.0s
 => => naming to docker.io/library/text-processor:latest                                                                                               0.0s
 => => unpacking to docker.io/library/text-processor:latest                                                                                            0.4s
PS C:\Users\aredl\DockerProject> docker images
REPOSITORY                                TAG                                                                           IMAGE ID       CREATED          SIZE
text-processor                            latest                                                                        5f37e852d759   11 seconds ago   227MB
docker/desktop-kubernetes                 kubernetes-v1.31.4-cni-v1.6.0-critools-v1.31.1-cri-dockerd-v0.3.15-1-debian   1405239673ef   2 months ago     577MB
registry.k8s.io/kube-apiserver            v1.31.4                                                                       ace6a943b058   2 months ago     125MB
registry.k8s.io/kube-controller-manager   v1.31.4                                                                       4bd1d4a449e7   2 months ago     118MB
registry.k8s.io/kube-scheduler            v1.31.4                                                                       1a3081cb7d21   2 months ago     90.8MB
registry.k8s.io/kube-proxy                v1.31.4                                                                       1739b3febca3   2 months ago     126MB
registry.k8s.io/etcd                      3.5.16-0                                                                      c6a9d11cc5c0   5 months ago     211MB
registry.k8s.io/coredns/coredns           v1.11.3                                                                       9caabbf6238b   7 months ago     85.1MB
registry.k8s.io/etcd                      3.5.15-0                                                                      a6dc63e6e8cf   7 months ago     208MB
registry.k8s.io/pause                     3.10                                                                          ee6521f290b2   9 months ago     1.06MB
docker/welcome-to-docker                  latest                                                                        eedaff45e3c7   15 months ago    29.5MB
docker/desktop-vpnkit-controller          dc331cb22850be0cdd97c84a9cfecaf44a1afb6e                                      7ecf567ea070   21 months ago    47MB
docker/desktop-storage-provisioner        v2.0                                                                          115d77efe6e2   3 years ago      59.2MB
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
deployment.apps/text-processor-deployment unchanged
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-8455fd77dd-ldfph   0/1     ImagePullBackOff   0          4m22s
text-processor-deployment-8455fd77dd-nkkvc   0/1     ImagePullBackOff   0          4m22s
PS C:\Users\aredl\DockerProject> docker login
Authenticating with existing credentials...
Login Succeeded
PS C:\Users\aredl\DockerProject> docker tag text-processor:latest anjaliaredla/text-processor:latest
PS C:\Users\aredl\DockerProject> docker push anjaliaredla/text-processor:latest
The push refers to repository [docker.io/anjaliaredla/text-processor]
3e975f5e670f: Pushed
4f4fb700ef54: Pushed
fb0009da06dd: Pushed
bbf333b6da4c: Pushed
8b0787314fda: Pushed
09f8c21e9f8e: Pushed
7cf63256a31a: Pushed
82a59f028fa3: Pushed
4d6850b9ca3f: Pushed
latest: digest: sha256:5f37e852d759c1636152cd37d2f8b31442e6bea49e18d18881c1af727a7c44dd size: 856
PS C:\Users\aredl\DockerProject> image: <your-dockerhub-username>/text-processor:latest
At line:1 char:8
+ image: <your-dockerhub-username>/text-processor:latest
+        ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

PS C:\Users\aredl\DockerProject> image: anjaliaredla/text-processor:latest
image: : The term 'image:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ image: anjaliaredla/text-processor:latest
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (image::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> kubectl rollout restart deployment text-processor-deployment
deployment.apps/text-processor-deployment restarted
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-7bdbfcc6bf-zvznq   0/1     ErrImagePull       0          4s
text-processor-deployment-8455fd77dd-ldfph   0/1     ImagePullBackOff   0          7m13s
text-processor-deployment-8455fd77dd-nkkvc   0/1     ImagePullBackOff   0          7m13s
PS C:\Users\aredl\DockerProject> kubectl describe pod text-processor-deployment-7bdbfcc6bf-zvznq   0/1
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'C:\Program Files\Docker\Docker\resources\bin\kubectl.exe get resource/<resource_name>' instead of 'C:\Program Files\Docker\Docker\resources\bin\kubectl.exe get resource resource/<resource_name>'
PS C:\Users\aredl\DockerProject> kubectl describe pod text-processor-deployment-7bdbfcc6bf-zvznq
Name:             text-processor-deployment-7bdbfcc6bf-zvznq
Namespace:        default
Priority:         0
Service Account:  default
Node:             docker-desktop/192.168.65.3
Start Time:       Thu, 27 Feb 2025 23:54:19 -0500
Labels:           app=text-processor
                  pod-template-hash=7bdbfcc6bf
Annotations:      kubectl.kubernetes.io/restartedAt: 2025-02-27T23:54:19-05:00
Status:           Pending
IP:               10.1.0.10
IPs:
  IP:           10.1.0.10
Controlled By:  ReplicaSet/text-processor-deployment-7bdbfcc6bf
Containers:
  text-processor:
    Container ID:
    Image:          text-processor:latest
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /home/data from text-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pg6tx (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  text-data:
    Type:          HostPath (bare host directory volume)
    Path:          /home/data
    HostPathType:
  kube-api-access-pg6tx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  70s                default-scheduler  Successfully assigned default/text-processor-deployment-7bdbfcc6bf-zvznq to docker-desktop
  Normal   Pulling    28s (x3 over 69s)  kubelet            Pulling image "text-processor:latest"
  Warning  Failed     28s (x3 over 68s)  kubelet            Failed to pull image "text-processor:latest": Error response from daemon: pull access denied for text-processor, repository does not exist or may require 'docker login'
  Warning  Failed     28s (x3 over 68s)  kubelet            Error: ErrImagePull
  Normal   BackOff    5s (x4 over 67s)   kubelet            Back-off pulling image "text-processor:latest"
  Warning  Failed     5s (x4 over 67s)   kubelet            Error: ImagePullBackOff
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-7bdbfcc6bf-zvznq   0/1     ErrImagePull       0          104s
text-processor-deployment-8455fd77dd-ldfph   0/1     ImagePullBackOff   0          8m53s
text-processor-deployment-8455fd77dd-nkkvc   0/1     ImagePullBackOff   0          8m53s
PS C:\Users\aredl\DockerProject> docker build -t text-processor:latest .
[+] Building 11.5s (11/11) FINISHED                                                                                                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 434B                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                     0.5s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [1/5] FROM docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.0s
 => => resolve docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.0s
 => [internal] load build context                                                                                                                      0.0s
 => => transferring context: 581B                                                                                                                      0.0s
 => CACHED [2/5] WORKDIR /home                                                                                                                         0.0s
 => CACHED [3/5] COPY scripts.py /home/scripts.py                                                                                                      0.0s
 => [4/5] COPY data /home/data                                                                                                                         0.1s
 => [5/5] RUN pip install --no-cache-dir requests nltk                                                                                                 8.7s
 => exporting to image                                                                                                                                 2.0s
 => => exporting layers                                                                                                                                1.3s
 => => exporting manifest sha256:7ab1004e74947d5d61ac64b9cf2a13508a9769f270f747a3116f3dc567acb8de                                                      0.0s
 => => exporting config sha256:578de4b87c8420b246c23b77beddb32ff71a9d972bf0087cdfcdebfce8193805                                                        0.0s
 => => exporting attestation manifest sha256:5b7c0f0b773e07f923fe89214061f55edb883dd7a0e4182c15cd5b835648a19c                                          0.0s
 => => exporting manifest list sha256:ad3596d846f790bb7850e893e4d4362c78538c838d3a4ba9b4849f3d60180538                                                 0.0s
 => => naming to docker.io/library/text-processor:latest                                                                                               0.0s
 => => unpacking to docker.io/library/text-processor:latest                                                                                            0.5s
PS C:\Users\aredl\DockerProject> image: text-processor:latest
image: : The term 'image:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
At line:1 char:1
+ image: text-processor:latest
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (image::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> docker build -t text-processor:latest .
[+] Building 12.4s (10/10) FINISHED                                                                                                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 434B                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                     0.6s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [1/5] FROM docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.1s
 => => resolve docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.0s
 => [internal] load build context                                                                                                                      0.0s
 => => transferring context: 581B                                                                                                                      0.0s
 => CACHED [2/5] WORKDIR /home                                                                                                                         0.0s
 => CACHED [3/5] COPY scripts.py /home/scripts.py                                                                                                      0.0s
 => [4/5] COPY data /home/data                                                                                                                         0.1s
 => [5/5] RUN pip install --no-cache-dir requests nltk                                                                                                 9.1s
 => exporting to image                                                                                                                                 2.3s
 => => exporting layers                                                                                                                                1.6s
 => => exporting manifest sha256:201380878bc5874bae6f11071cc50398f829791c0083dcf3d4290920dd26ae37                                                      0.0s
 => => exporting config sha256:59bf767d8f1fbbdf38be87f471fca8d145dc9db14600562509da91b1954123b7                                                        0.0s
 => => exporting attestation manifest sha256:fa118a720ca94f378e6cdf63a9cbe5d7de7e860e473a4b30e6fb23a44ab4c23a                                          0.0s
 => => exporting manifest list sha256:d78282a66f599445942493b1cf9ffb5a7ba3da8ef61a8b663be29f679f01cdb4                                                 0.0s
 => => naming to docker.io/library/text-processor:latest                                                                                               0.0s
 => => unpacking to docker.io/library/text-processor:latest                                                                                            0.5s
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-7bdbfcc6bf-zvznq   0/1     ImagePullBackOff   0          5m9s
text-processor-deployment-8455fd77dd-ldfph   0/1     ImagePullBackOff   0          12m
text-processor-deployment-8455fd77dd-nkkvc   0/1     ImagePullBackOff   0          12m
PS C:\Users\aredl\DockerProject> kubectl rollout restart deployment text-processor-deployment
deployment.apps/text-processor-deployment restarted
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-7bdbfcc6bf-zvznq   0/1     ImagePullBackOff   0          6m24s
text-processor-deployment-8455fd77dd-nkkvc   0/1     ImagePullBackOff   0          13m
text-processor-deployment-8599c9657b-kfmlb   0/1     ErrImagePull       0          3s
PS C:\Users\aredl\DockerProject> docker login
Authenticating with existing credentials...
Login Succeeded
PS C:\Users\aredl\DockerProject> docker push anjaliaredla/text-processor:latest
The push refers to repository [docker.io/anjaliaredla/text-processor]
bbf333b6da4c: Layer already exists
4f4fb700ef54: Layer already exists
4d6850b9ca3f: Layer already exists
7cf63256a31a: Layer already exists
fb0009da06dd: Layer already exists
82a59f028fa3: Layer already exists
8b0787314fda: Already exists
3e975f5e670f: Layer already exists
09f8c21e9f8e: Layer already exists
latest: digest: sha256:5f37e852d759c1636152cd37d2f8b31442e6bea49e18d18881c1af727a7c44dd size: 856
PS C:\Users\aredl\DockerProject> kubectl rollout restart deployment text-processor-deployment
deployment.apps/text-processor-deployment restarted
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
text-processor-deployment-7bdbfcc6bf-zvznq   0/1     ImagePullBackOff   0          7m47s
text-processor-deployment-8599c9657b-kfmlb   0/1     ImagePullBackOff   0          86s
text-processor-deployment-9bbc78f6c-5btdl    0/1     ErrImagePull       0          3s
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
deployment.apps/text-processor-deployment configured
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-56fb4fd848-r59mw   0/1     ContainerCreating   0          3s
text-processor-deployment-8599c9657b-kfmlb   0/1     ImagePullBackOff    0          6m34s
text-processor-deployment-9bbc78f6c-5btdl    0/1     ImagePullBackOff    0          5m11s
PS C:\Users\aredl\DockerProject> kubectl rollout restart deployment text-processor-deployment
deployment.apps/text-processor-deployment restarted
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-56fb4fd848-r59mw   0/1     ContainerCreating   0          11s
text-processor-deployment-7c69c84486-l2tdb   0/1     ContainerCreating   0          3s
text-processor-deployment-9bbc78f6c-5btdl    0/1     ImagePullBackOff    0          5m19s
PS C:\Users\aredl\DockerProject> docker build -t text-processor:latest .
[+] Building 13.8s (11/11) FINISHED                                                                                                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 434B                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                     0.4s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [1/5] FROM docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.0s
 => => resolve docker.io/library/python:3.9-slim@sha256:d1fd807555208707ec95b284afd10048d0737e84b5f2d6fdcbed2922b9284b56                               0.0s
 => [internal] load build context                                                                                                                      0.0s
 => => transferring context: 580B                                                                                                                      0.0s
 => CACHED [2/5] WORKDIR /home                                                                                                                         0.0s
 => CACHED [3/5] COPY scripts.py /home/scripts.py                                                                                                      0.0s
 => [4/5] COPY data /home/data                                                                                                                         0.1s
 => [5/5] RUN pip install --no-cache-dir requests nltk                                                                                                10.4s
 => exporting to image                                                                                                                                 2.5s
 => => exporting layers                                                                                                                                1.7s
 => => exporting manifest sha256:18cc3380ec2d4910b1a92cc9d4b5f52b6b3f01191b03b2dca0a87741f0672454                                                      0.0s
 => => exporting config sha256:4394affd85a92603e2387f6ceae2c5fdacdea5ee607f1b4d4b994b758bfd0769                                                        0.0s
 => => exporting attestation manifest sha256:bb69b09b0677570e4fa0bdbe713df94b4dfb487b867546e85ceef4bab329e63d                                          0.0s
 => => exporting manifest list sha256:c5342b4ebac8cd1859bd2ca1ff2daeb8dfc72fe1ed012fe7b66cb013ebd64d11                                                 0.0s
 => => naming to docker.io/library/text-processor:latest                                                                                               0.0s
 => => unpacking to docker.io/library/text-processor:latest                                                                                            0.6s
PS C:\Users\aredl\DockerProject> minikube image load text-processor:latest
minikube : The term 'minikube' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ minikube image load text-processor:latest
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (minikube:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\aredl\DockerProject> docker tag text-processor:latest <your-dockerhub-username>/text-processor:latest
At line:1 char:34
+ docker tag text-processor:latest <your-dockerhub-username>/text-proce ...
+                                  ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

PS C:\Users\aredl\DockerProject> docker push <your-dockerhub-username>/text-processor:latest
At line:1 char:13
+ docker push <your-dockerhub-username>/text-processor:latest
+             ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

PS C:\Users\aredl\DockerProject> docker tag text-processor:latest anjaliaredla/text-processor:latest
PS C:\Users\aredl\DockerProject> docker push anjaliaredla/text-processor:latest
The push refers to repository [docker.io/anjaliaredla/text-processor]
55825005b3b0: Pushed
12bc8792ccd2: Pushed
bbf333b6da4c: Layer already exists
fb0009da06dd: Layer already exists
09f8c21e9f8e: Layer already exists
4f4fb700ef54: Layer already exists
c96d85a2afb7: Pushed
7cf63256a31a: Layer already exists
82a59f028fa3: Layer already exists
latest: digest: sha256:c5342b4ebac8cd1859bd2ca1ff2daeb8dfc72fe1ed012fe7b66cb013ebd64d11 size: 856
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
deployment.apps/text-processor-deployment configured
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-56fb4fd848-r59mw   0/1     ContainerCreating   0          2m56s
text-processor-deployment-6f978cc685-wn4dm   0/1     ContainerCreating   0          14s
text-processor-deployment-7c69c84486-l2tdb   0/1     ContainerCreating   0          2m48s
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-56fb4fd848-r59mw   0/1     ContainerCreating   0          3m4s
text-processor-deployment-6f978cc685-wn4dm   0/1     ContainerCreating   0          22s
text-processor-deployment-7c69c84486-l2tdb   0/1     ContainerCreating   0          2m56s
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-56fb4fd848-r59mw   0/1     ContainerCreating   0          3m6s
text-processor-deployment-6f978cc685-wn4dm   0/1     ContainerCreating   0          24s
text-processor-deployment-7c69c84486-l2tdb   0/1     ContainerCreating   0          2m58s
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-56fb4fd848-r59mw   0/1     ContainerCreating   0          3m10s
text-processor-deployment-6f978cc685-wn4dm   0/1     ContainerCreating   0          28s
text-processor-deployment-7c69c84486-l2tdb   0/1     ContainerCreating   0          3m2s
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-56fb4fd848-r59mw   0/1     ContainerCreating   0          4m17s
text-processor-deployment-6f978cc685-wn4dm   0/1     ContainerCreating   0          95s
text-processor-deployment-7c69c84486-l2tdb   0/1     ContainerCreating   0          4m9s
PS C:\Users\aredl\DockerProject> kubectl describe text-processor-deployment-56fb4fd848-r59mw
error: the server doesn't have a resource type "text-processor-deployment-56fb4fd848-r59mw"
PS C:\Users\aredl\DockerProject> kubectl describe pod text-processor-deployment-56fb4fd848-r59mw
Name:             text-processor-deployment-56fb4fd848-r59mw
Namespace:        default
Priority:         0
Service Account:  default
Node:             docker-desktop/192.168.65.3
Start Time:       Fri, 28 Feb 2025 00:07:11 -0500
Labels:           app=text-processor
                  pod-template-hash=56fb4fd848
Annotations:      kubectl.kubernetes.io/restartedAt: 2025-02-28T00:02:03-05:00
Status:           Pending
IP:
IPs:              <none>
Controlled By:    ReplicaSet/text-processor-deployment-56fb4fd848
Containers:
  text-processor:
    Container ID:
    Image:          text-processor:latest
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /home/data from data-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x6gs7 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   False
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  data-volume:
    Type:          HostPath (bare host directory volume)
    Path:          C:\Users\aredl\DockerProject\data
    HostPathType:  Directory
  kube-api-access-x6gs7:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    4m57s                 default-scheduler  Successfully assigned default/text-processor-deployment-56fb4fd848-r59mw to docker-desktop
  Warning  FailedMount  47s (x10 over 4m56s)  kubelet            MountVolume.SetUp failed for volume "data-volume" : hostPath type check failed: C:\Users\aredl\DockerProject\data is not a directory
PS C:\Users\aredl\DockerProject> kubectl apply -f deployment.yaml
deployment.apps/text-processor-deployment configured
PS C:\Users\aredl\DockerProject> kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
text-processor-deployment-6f978cc685-wn4dm   0/1     ContainerCreating   0          5m25s
text-processor-deployment-7c69c84486-l2tdb   0/1     ContainerCreating   0          7m59s
text-processor-deployment-bb6645bdf-rs5d5    0/1     ContainerCreating   0          3s
PS C:\Users\aredl\DockerProject> kubectl describe pod text-processor-deployment-56fb4fd848-r59mw
Error from server (NotFound): pods "text-processor-deployment-56fb4fd848-r59mw" not found
PS C:\Users\aredl\DockerProject> kubectl describe pod text-processor-deployment-56fb4fd848-r59mw
Error from server (NotFound): pods "text-processor-deployment-56fb4fd848-r59mw" not found
PS C:\Users\aredl\DockerProject>